import { Options } from '@appsemble/node-utils/server/types.js';

import {
  createSettings,
  createTheme,
  getApp,
  getAppBlockStyles,
  getAppDetails,
  getAppIcon,
  getAppMessages,
  getAppResources,
  getAppScreenshots,
  getAppStyles,
  getAppUrl,
  getBlockAsset,
  getBlocksAssetsPaths,
  getCsp,
  getDbUpdated,
  getHost,
  getTheme,
} from './index.js';

export const options: Options = {
  createSettings,
  createTheme,
  getApp,
  getAppBlockStyles,
  getAppDetails,
  getAppIcon,
  getAppMessages,
  getAppResources,
  getAppScreenshots,
  getAppStyles,
  getAppUrl,
  getBlockAsset,
  getBlocksAssetsPaths,
  getCsp,
  getDbUpdated,
  getHost,
  getTheme,
};
