/**
 * OAuth2 client credentials as they are returned by the API.
 */
export interface OAuth2ClientCredentials {
  /**
   * When the client credentials were created.
   */
  $created?: string;

  /**
   * The autogenerated `client_id` of the client credentials.
   */
  id: string;

  /**
   * The autogenerated `client_secret` of the client credentials.
   *
   * This is only available upon creation.
   */
  secret?: string;

  /**
   * A human readable description of the client description.
   */
  description: string;

  /**
   * The expiration date of the client credentials.
   */
  expires?: string;

  /**
   * The OAuth2 scopes these client credentials have been granted.
   */
  scopes: string[];
}
