/**
 * A user email registration.
 */
export interface UserEmail {
  /**
   * The registered email address
   */
  email: string;

  /**
   * Wether or not the email address has been verified.
   */
  verified: boolean;

  /**
   * Whether or not this is the user’s primary email address.
   */
  primary?: boolean;
}

/**
 * A user as they are represented by the API.
 */
export interface User {
  /**
   * A list of email addresses that belong to the user.
   */
  emails: UserEmail[];
}

/**
 * OAuth2 client credentials as they are returned by the API.
 */
export interface OAuth2ClientCredentials {
  /**
   * When the client credentials were created.
   */
  $created?: string;

  /**
   * The autogenerated `client_id` of the client credentials.
   */
  id: string;

  /**
   * The autogenerated `client_secret` of the client credentials.
   *
   * This is only available upon creation.
   */
  secret?: string;

  /**
   * A human readable description of the client description.
   */
  description: string;

  /**
   * The expiration date of the client credentials.
   */
  expires?: string;

  /**
   * The OAuth2 scopes these client credentials have been granted.
   */
  scopes: string[];
}
