import { type OpenAPIV3 } from 'openapi-types';

export const AppSamlSecret: OpenAPIV3.NonArraySchemaObject = {
  type: 'object',
  description: 'Settings for login in apps using third party SAML providers',
  required: ['entityId', 'icon', 'idpCertificate', 'name', 'ssoUrl'],
  additionalProperties: false,
  properties: {
    id: {
      type: 'number',
      description: 'An autogenerated ID.',
      readOnly: true,
    },
    entityId: {
      type: 'string',
      format: 'uri',
      description: 'The URL where the identity provider metadata is hosted.',
    },
    ssoUrl: {
      type: 'string',
      format: 'uri',
      description: 'The URL where the user is redirected to log in.',
    },
    idpCertificate: {
      type: 'string',
      description: 'The certificate of the identity provider.',
    },
    icon: {
      type: 'string',
      description: 'A Font Awesome icon which represents the SAML provider.',
    },
    name: {
      type: 'string',
      description: 'A display name which represents the SAML provider.',
    },
    emailAttribute: {
      type: 'string',
      description: 'The SAML attribute that contains the user email address.',
    },
    emailVerifiedAttribute: {
      type: 'string',
      description: 'The SAML attribute that contains whether the email address is verified.',
    },
    nameAttribute: {
      type: 'string',
      description: 'The SAML attribute that contains the user display name.',
    },
    groupAttribute: {
      type: 'string',
      description: 'The SAML attribute that contains the external groups for the user.',
    },
    objectIdAttribute: {
      type: 'string',
      description: 'The SAML attribute that contains the external user identifier.',
    },
    roleMappings: {
      type: 'array',
      description: 'Optional exact external-group to app-role mappings.',
      items: {
        type: 'object',
        description: 'A mapping from one exact external group value to one app role.',
        required: ['group', 'role'],
        additionalProperties: false,
        properties: {
          group: {
            type: 'string',
            description: 'The exact external group value to match.',
          },
          role: {
            type: 'string',
            description: 'The app role to assign when the external group matches.',
          },
        },
      },
    },
    spCertificate: {
      type: 'string',
      description: 'The generated SAML service provider certificate.',
      readOnly: true,
    },
    updated: {
      type: 'string',
      format: 'date-time',
      description: 'When the secret was last updated.',
    },
  },
};
