import { type OpenAPIV3 } from 'openapi-types';

export const AppWebhookSecret: OpenAPIV3.NonArraySchemaObject = {
  type: 'object',
  description: 'App webhook secret settings',
  additionalProperties: false,
  properties: {
    id: {
      type: 'number',
      description: 'An autogenerated ID.',
      readOnly: true,
    },
    name: {
      type: 'string',
      description: 'An optional name to give extra clarity what the secret is used for.',
    },
    secret: {
      type: 'string',
      description: 'The autogenerated secret to authenticate the webhook caller with.',
    },
  },
};
