import { type OpenAPIV3 } from 'openapi-types';

export const FilterParametersDefinition: OpenAPIV3.NonArraySchemaObject = {
  type: 'object',
  description: 'An object describing the names of the events the block can listen and emit to.',
  additionalProperties: false,
  properties: {
    type: {
      enum: [
        'Boolean',
        'Byte',
        'Date',
        'DateTimeOffset',
        'Decimal',
        'Double',
        'Duration',
        'Guid',
        'Int16',
        'Int32',
        'Int64',
        'SByte',
        'Single',
        'Stream',
        'String',
        'TimeOfDay',
        'Geography',
        'GeographyPoint',
        'GeographyLineString',
        'GeographyPolygon',
        'GeographyMultiPoint',
        'GeographyMultiLineString',
        'GeographyMultiPolygon',
        'GeographyCollection',
        'Geometry',
        'GeometryPoint',
        'GeometryLineString',
        'GeometryPolygon',
        'GeometryMultiPoint',
        'GeometryMultiLineString',
        'GeometryMultiPolygon',
        'GeometryCollection',
      ],
    },
    value: { $ref: '#/components/schemas/RemapperDefinition' },
    comparator: {
      enum: ['eq', 'ge', 'gt', 'le', 'lt', 'ne'],
    },
  },
};
