context:
  development:
    organization: appsemble
    remote: http://localhost:9999
    visibility: public
  production:
    id: 14
    organization: appsemble
    remote: https://appsemble.app
    visibility: public
  review:
    organization: appsemble
    visibility: public
  staging:
    id: 14
    organization: appsemble
    remote: https://staging.appsemble.review
    visibility: public
  e2e:
    organization: appsemble
    visibility: public
