{{/*
Expand the name of the chart.
*/}}
{{- define "appsemble.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "appsemble.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "appsemble.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create the default labels for a template indented with 4 spaces.
*/}}
{{- define "appsemble.labels" -}}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "appsemble.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "appsemble.chart" . }}
{{- end -}}

{{/*
Create annotations for GitLab monitoring.
*/}}
{{- define "appsemble.gitlab" -}}
{{ with .Values.gitlab.app }}
app.gitlab.com/app: {{ . | quote }}
{{ end }}
{{ with .Values.gitlab.env }}
app.gitlab.com/env: {{ . | quote }}
{{ end }}
{{- end -}}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "appsemble.tag" -}}
{{- default .Chart.AppVersion .Values.image.tag -}}
{{- end -}}

{{/*
Get the protocol on which Appsemble is accessible.
*/}}
{{- define "appsemble.protocol" -}}
{{- if .Values.ingress.enabled -}}
http{{ if or .Values.forceProtocolHttps .Values.ingress.tls }}s{{ end }}://
{{- else if .Values.route.enabled -}}
https://
{{- else -}}
http://
{{- end -}}
{{- end -}}

{{/*
Get the external host on which Appsemble is accessible.
*/}}
{{- define "appsemble.host" -}}
{{- if .Values.ingress.enabled -}}
{{ include "appsemble.protocol" . }}{{ .Values.ingress.host }}
{{- else if .Values.route.enabled -}}
{{ include "appsemble.protocol" . }}{{ .Values.route.host }}
{{- else -}}
http://{{ include "appsemble.fullname" . }}
{{- end -}}
{{- end -}}

{{/*
Configure the environment variables for Appsemble to connect with the Postgres instance,
through PgBouncer when it is enabled.
*/}}
{{- define "appsemble.postgres" -}}
- name: DATABASE_HOST
  value: {{ ternary (include "appsemble.pgbouncer.fullname" .) .Values.postgresql.fullnameOverride .Values.pgbouncer.enabled | quote }}
{{ if .Values.postgresSSL }}
- name: DATABASE_SSL
  value: 'true'
{{ end }}
- name: DATABASE_PORT
  value: {{ ternary .Values.pgbouncer.service.port .Values.global.postgresql.service.ports.postgresql .Values.pgbouncer.enabled | quote }}
{{ if .Values.pgbouncer.enabled }}
- name: DATABASE_DIRECT_HOST
  value: {{ .Values.postgresql.fullnameOverride | quote }}
- name: DATABASE_DIRECT_PORT
  value: {{ .Values.global.postgresql.service.ports.postgresql | quote }}
{{ end }}
- name: DATABASE_NAME
  value: {{ .Values.global.postgresql.auth.database | quote }}
- name: DATABASE_USER
  value: {{ .Values.global.postgresql.auth.username | quote }}
- name: DATABASE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ .Values.global.postgresql.auth.existingSecret | quote }}
      key: {{ .Values.global.postgresql.auth.secretKeys.userPasswordKey | quote }}
{{- end -}}

{{/*
Get the PgBouncer service name.
*/}}
{{- define "appsemble.pgbouncer.fullname" -}}
{{- printf "%s-pgbouncer" (include "appsemble.fullname" .) -}}
{{- end -}}

{{/*
Get the TLS secret PgBouncer should use for client-facing TLS.
*/}}
{{- define "appsemble.pgbouncer.tlsSecretName" -}}
{{- if .Values.pgbouncer.tls.existingSecret -}}
{{- .Values.pgbouncer.tls.existingSecret -}}
{{- else if .Values.pgbouncer.tls.autoGenerated -}}
{{- printf "%s-tls" (include "appsemble.pgbouncer.fullname" .) -}}
{{- else -}}
{{- required "pgbouncer.tls.existingSecret is required when pgbouncer.tls.autoGenerated is false and postgresSSL is true" .Values.pgbouncer.tls.existingSecret -}}
{{- end -}}
{{- end -}}

{{/*
Configure the environment variables for Appsemble to connect with the Minio instance.
*/}}
{{- define "appsemble.s3" -}}
{{- if .Values.minio.apiIngress.enabled }}
- name: S3_HOST
  value: {{ .Values.minio.apiIngress.hostname | quote }}
- name: S3_PORT
  value: "443"
{{- else }}
{{- with .Values.minio.auth.existingSecret }}
- name: S3_HOST
  valueFrom:
    secretKeyRef:
      name: {{ . | quote }}
      key: host
- name: S3_PORT
  valueFrom:
    secretKeyRef:
      name: {{ . | quote }}
      key: port
{{- end }}
{{- end }}
{{- with .Values.minio.auth.existingSecret }}
- name: S3_SECURE
  valueFrom:
    secretKeyRef:
      name: {{ . | quote }}
      key: secure
- name: S3_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: {{ . | quote }}
      key: access-key
- name: S3_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: {{ . | quote }}
      key: secret-key
{{- end }}
{{- end -}}

{{/*
Get the Valkey host for bundled or explicitly configured external Valkey.
*/}}
{{- define "appsemble.valkey.host" -}}
{{- if .Values.valkey.enabled -}}
{{- default (printf "%s-valkey" .Release.Name) .Values.valkey.fullnameOverride -}}
{{- else -}}
{{- required "externalValkey.host is required when valkey.enabled is false" .Values.externalValkey.host -}}
{{- end -}}
{{- end -}}

{{/*
Get the Valkey credential secret for bundled or external Valkey.
*/}}
{{- define "appsemble.valkey.secret" -}}
{{- if .Values.valkey.enabled -}}
{{- required "valkey.auth.usersExistingSecret is required when valkey.enabled is true" .Values.valkey.auth.usersExistingSecret -}}
{{- else -}}
{{- required "externalValkey.existingSecret is required when valkey.enabled is false" .Values.externalValkey.existingSecret -}}
{{- end -}}
{{- end -}}

{{/*
Get the Valkey credential secret key for bundled or external Valkey.
*/}}
{{- define "appsemble.valkey.passwordKey" -}}
{{- if .Values.valkey.enabled -}}
{{- required "valkey.auth.aclUsers.default.passwordKey is required when valkey.enabled is true" .Values.valkey.auth.aclUsers.default.passwordKey -}}
{{- else -}}
{{- required "externalValkey.passwordKey is required when valkey.enabled is false" .Values.externalValkey.passwordKey -}}
{{- end -}}
{{- end -}}

{{/*
Configure the environment variables for Appsemble to connect with Valkey.
*/}}
{{- define "appsemble.valkey" -}}
- name: VALKEY_HOST
  value: {{ include "appsemble.valkey.host" . | quote }}
- name: VALKEY_PORT
  value: {{ ternary .Values.valkey.service.port .Values.externalValkey.port .Values.valkey.enabled | quote }}
- name: VALKEY_USERNAME
  value: {{ ternary "default" .Values.externalValkey.username .Values.valkey.enabled | quote }}
- name: VALKEY_TLS
  value: {{ ternary false .Values.externalValkey.tls .Values.valkey.enabled | quote }}
- name: VALKEY_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ include "appsemble.valkey.secret" . | quote }}
      key: {{ include "appsemble.valkey.passwordKey" . | quote }}
{{- end -}}

{{/*
Configure the environment variables for Appsemble to enable backups.
*/}}
{{- define "appsemble.backups" -}}
{{- if .Values.backups.enabled }}
- name: BACKUPS_BUCKET
  value: {{ .Values.backups.bucket | quote }}
- name: BACKUPS_FILENAME
  value: {{ .Values.backups.filename | quote }}
- name: BACKUPS_HOST
  value: {{ .Values.backups.host | quote }}
- name: BACKUPS_PORT
  value: {{ .Values.backups.port | quote }}
- name: BACKUPS_SECURE
  value: {{ .Values.backups.secure | quote }}
{{- with .Values.backups.existingSecret }}
- name: BACKUPS_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: {{ . | quote }}
      key: access-key
- name: BACKUPS_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: {{ . | quote }}
      key: secret-key
{{- end }}
{{- end }}
{{- end -}}


{{/*
Configure the environment variable for Appsemble to authenticate incoming Stripe webhooks.
*/}}
{{- define "appsemble.stripeWebhookSecret" -}}
{{- with .Values.stripeWebhookSecret }}
- name: STRIPE_WEBHOOK_SECRET
  valueFrom:
    secretKeyRef:
      name: {{ . | quote }}
      key: stripe-webhook-secret
{{- end }}
{{- end }}

{{/*
Configure the environment variable for Appsemble to connect to Stripe.
*/}}
{{- define "appsemble.stripeApiSecretKey" -}}
{{- with .Values.stripeApiSecretKey }}
- name: STRIPE_API_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: {{ . | quote }}
      key: stripe-api-secret-key
{{- end }}
{{- end }}

{{/*
Configure the environment variables for Sentry.
*/}}
{{- define "appsemble.sentry" -}}
{{ with .Values.sentry }}
- name: SENTRY_DSN
  valueFrom:
    secretKeyRef:
      name: {{ .secret | quote }}
      key: dsn
{{ with .environment }}
- name: SENTRY_ENVIRONMENT
  value: {{ . | quote }}
{{ end }}
{{ with .allowedDomains }}
- name: SENTRY_ALLOWED_DOMAINS
  value: {{ join "," . | quote }}
{{ end }}
{{ end }}
{{- end -}}
