{{- if .Values.ingress.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "appsemble.fullname" . }}-cleanup-resources-and-assets
  labels:
    {{ include "appsemble.labels" . }}
spec:
  schedule: 0 23 * * * # Run every day at 23:00:00
  successfulJobsHistoryLimit: {{ .Values.cronjob.jobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.jobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            {{ include "appsemble.gitlab" . | indent 12 }}
        spec:
          restartPolicy: Never
          containers:
            - name: {{ include "appsemble.fullname" . }}-cronjob-cleanup-resources-and-assets
              image: "{{ .Values.image.repository }}:{{ include "appsemble.tag" . }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              securityContext:
                readOnlyRootFilesystem: true
              args:
                - cleanup-resources-and-assets
                - -vv
              env:
{{ include "appsemble.postgres" . | indent 16 }}
{{ end }}
