{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "appsemble.fullname" . }}
  labels:
    {{ include "appsemble.labels" . }}
  annotations:
    {{ with .Values.ingress.annotations }}
    {{ toYaml . | nindent 4 }}
    {{ end }}

    {{ with .Values.ingress.issuer }}
    cert-manager.io/issuer: {{ . | quote }}
    {{ end }}
    {{ with .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ . | quote }}
    {{ end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
    - hosts:
      - '*.{{ .Values.ingress.host }}'
      secretName: {{ .Values.ingress.tls.wildcardSecretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "appsemble.fullname" . }}
                port:
                  name: http
    - host: '*.{{ .Values.ingress.host }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "appsemble.fullname" . }}
                port:
                  name: http
    - host: 'mailpit.{{ .Values.ingress.host }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "appsemble.fullname" . }}-mailpit-http
                port:
                  name: http
    - host: 'minio.{{ .Values.ingress.host }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "appsemble.fullname" . }}-minio
                port:
                  name: minio-console
{{- end }}
