{{ if .Values.provision }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "appsemble.fullname" . }}-provision
  labels:
    {{ include "appsemble.labels" . }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: '1'
    {{ include "appsemble.gitlab" . | indent 4 }}
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "appsemble.fullname" . }}-serviceaccount
      containers:
        - name: {{ include "appsemble.fullname" . }}-provision
          image: "{{ .Values.image.repository }}:{{ include "appsemble.tag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            readOnlyRootFilesystem: true
          resources:
            {{- toYaml .Values.resources.jobs | nindent 12 }}
          args:
            - provision
            - --organization-id
            - {{ .Values.provision.organization.id | quote }}
            - --organization-role
            - {{ .Values.provision.user.organizationRole | quote }}
            - --organization-subscription
            - {{ .Values.provision.organization.subscription | quote }}
            - --user-email
            - {{ .Values.provision.user.email | quote }}
            - --user-name
            - {{ .Values.provision.user.name | quote }}
            - --user-password
            - {{ .Values.provision.user.password | quote }}
            - --user-timezone
            - {{ .Values.provision.user.timezone | quote }}
            - --client-credentials
            - {{ .Values.provision.user.clientCredentials | quote }}
            {{- if .Values.skipCustomDomains }}
            - --skip-custom-domains
            {{- end }}
            - -vv
          env:
            - name: DATABASE_HOST
              value: {{ .Values.postgresql.fullnameOverride }}
            - name: DATABASE_PORT
              value: {{ .Values.global.postgresql.service.ports.postgresql | quote }}
            - name: DATABASE_NAME
              value: {{ .Values.global.postgresql.auth.database }}
            - name: DATABASE_USER
              value: {{ .Values.global.postgresql.auth.username }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.postgresql.auth.existingSecret }}
                  key: {{ .Values.global.postgresql.auth.secretKeys.userPasswordKey | quote }}
            {{- if .Values.ingress.enabled }}
            - name: APP_DOMAIN_STRATEGY
              value: kubernetes-ingress
            - name: INGRESS_CLASS_NAME
              value: {{ .Values.ingress.className | quote }}
            - name: INGRESS_ANNOTATIONS
              value: {{ .Values.ingress.annotations | toJson | quote }}
            - name: SERVICE_NAME
              value: {{ include "appsemble.fullname" . }}
            - name: SERVICE_PORT
              value: http
            - name: HOST
              value: {{ include "appsemble.host" . }}
            {{- with .Values.ingress.issuer }}
            - name: ISSUER
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.ingress.clusterIssuer }}
            - name: CLUSTER_ISSUER
              value: {{ . | quote }}
            {{- end }}
            {{- end }}
{{ end }}
