{{- if .Values.ingress.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "appsemble.fullname" . }}
  labels:
    {{ include "appsemble.labels" . }}
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - deletecollection
      - patch
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - deletecollection
      - patch
      - list
      - delete
  - apiGroups:
      - cert-manager.io
    resources:
      - certificates
    verbs:
      - list
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ''
    resources:
      - pods/log
    verbs:
      - get
{{ end }}
