context:
  development:
    organization: appsemble
    remote: http://localhost:9999
    visibility: public
    resources: true
  production:
    id: 3
    organization: appsemble
    remote: https://appsemble.app
    visibility: public
    resources: true
  review:
    organization: appsemble
    visibility: public
    resources: true
  staging:
    id: 3
    organization: appsemble
    remote: https://staging.appsemble.eu
    visibility: public
    resources: true
  e2e:
    organization: appsemble
    visibility: public
    resources: true
