// Generated from @fortawesome/fontawesome-free 6.7.2 by `npm run scripts -- generate-font-awesome`.
// Don't edit by hand.

/**
 * Font Awesome alias names, mapped to the name of the icon they render.
 */
export const fontAwesomeAliases: Record<string, string> = {
  ad: 'rectangle-ad',
  add: 'plus',
  adjust: 'circle-half-stroke',
  'air-freshener': 'spray-can-sparkles',
  allergies: 'hand-dots',
  ambulance: 'truck-medical',
  'american-sign-language-interpreting': 'hands-asl-interpreting',
  'angle-double-down': 'angles-down',
  'angle-double-left': 'angles-left',
  'angle-double-right': 'angles-right',
  'angle-double-up': 'angles-up',
  angry: 'face-angry',
  'apple-alt': 'apple-whole',
  archive: 'box-archive',
  'area-chart': 'chart-area',
  'arrow-alt-circle-down': 'circle-down',
  'arrow-alt-circle-left': 'circle-left',
  'arrow-alt-circle-right': 'circle-right',
  'arrow-alt-circle-up': 'circle-up',
  'arrow-circle-down': 'circle-arrow-down',
  'arrow-circle-left': 'circle-arrow-left',
  'arrow-circle-right': 'circle-arrow-right',
  'arrow-circle-up': 'circle-arrow-up',
  'arrow-left-rotate': 'arrow-rotate-left',
  'arrow-right-from-file': 'file-export',
  'arrow-right-rotate': 'arrow-rotate-right',
  'arrow-right-to-file': 'file-import',
  'arrow-rotate-back': 'arrow-rotate-left',
  'arrow-rotate-backward': 'arrow-rotate-left',
  'arrow-rotate-forward': 'arrow-rotate-right',
  arrows: 'arrows-up-down-left-right',
  'arrows-alt': 'up-down-left-right',
  'arrows-alt-h': 'left-right',
  'arrows-alt-v': 'up-down',
  'arrows-h': 'arrows-left-right',
  'arrows-v': 'arrows-up-down',
  'asl-interpreting': 'hands-asl-interpreting',
  'assistive-listening-systems': 'ear-listen',
  atlas: 'book-atlas',
  automobile: 'car',
  backspace: 'delete-left',
  'balance-scale': 'scale-balanced',
  'balance-scale-left': 'scale-unbalanced',
  'balance-scale-right': 'scale-unbalanced-flip',
  'band-aid': 'bandage',
  bank: 'building-columns',
  'bar-chart': 'chart-bar',
  'baseball-ball': 'baseball',
  'basketball-ball': 'basketball',
  bathtub: 'bath',
  battery: 'battery-full',
  'battery-0': 'battery-empty',
  'battery-2': 'battery-quarter',
  'battery-3': 'battery-half',
  'battery-4': 'battery-three-quarters',
  'battery-5': 'battery-full',
  'battery-car': 'car-battery',
  beer: 'beer-mug-empty',
  'behance-square': 'square-behance',
  bible: 'book-bible',
  biking: 'person-biking',
  'birthday-cake': 'cake-candles',
  blackboard: 'chalkboard',
  blind: 'person-walking-with-cane',
  'book-dead': 'book-skull',
  'book-reader': 'book-open-reader',
  'border-style': 'border-top-left',
  boxes: 'boxes-stacked',
  'boxes-alt': 'boxes-stacked',
  'briefcase-clock': 'business-time',
  'broadcast-tower': 'tower-broadcast',
  burn: 'fire-flame-simple',
  'bus-alt': 'bus-simple',
  cab: 'taxi',
  cake: 'cake-candles',
  'calendar-alt': 'calendar-days',
  'calendar-times': 'calendar-xmark',
  'camera-alt': 'camera',
  cancel: 'ban',
  'car-alt': 'car-rear',
  'car-crash': 'car-burst',
  'caret-square-down': 'square-caret-down',
  'caret-square-left': 'square-caret-left',
  'caret-square-right': 'square-caret-right',
  'caret-square-up': 'square-caret-up',
  'carriage-baby': 'baby-carriage',
  chain: 'link',
  'chain-broken': 'link-slash',
  'chain-slash': 'link-slash',
  'chalkboard-teacher': 'chalkboard-user',
  'check-circle': 'circle-check',
  'check-square': 'square-check',
  'chevron-circle-down': 'circle-chevron-down',
  'chevron-circle-left': 'circle-chevron-left',
  'chevron-circle-right': 'circle-chevron-right',
  'chevron-circle-up': 'circle-chevron-up',
  'child-rifle': 'child-combatant',
  'clinic-medical': 'house-chimney-medical',
  'clock-four': 'clock',
  close: 'xmark',
  'cloud-download': 'cloud-arrow-down',
  'cloud-download-alt': 'cloud-arrow-down',
  'cloud-upload': 'cloud-arrow-up',
  'cloud-upload-alt': 'cloud-arrow-up',
  cny: 'yen-sign',
  cocktail: 'martini-glass-citrus',
  coffee: 'mug-saucer',
  cog: 'gear',
  cogs: 'gears',
  columns: 'table-columns',
  'comment-alt': 'message',
  commenting: 'comment-dots',
  'compress-alt': 'down-left-and-up-right-to-center',
  'compress-arrows-alt': 'minimize',
  'concierge-bell': 'bell-concierge',
  'contact-book': 'address-book',
  'contact-card': 'address-card',
  'credit-card-alt': 'credit-card',
  'crop-alt': 'crop-simple',
  cut: 'scissors',
  cutlery: 'utensils',
  dashboard: 'gauge',
  deaf: 'ear-deaf',
  deafness: 'ear-deaf',
  dedent: 'outdent',
  'desktop-alt': 'desktop',
  diagnoses: 'person-dots-from-line',
  digging: 'person-digging',
  'digital-tachograph': 'tachograph-digital',
  directions: 'diamond-turn-right',
  dizzy: 'face-dizzy',
  dollar: 'dollar-sign',
  'dolly-box': 'dolly',
  'dolly-flatbed': 'cart-flatbed',
  donate: 'circle-dollar-to-slot',
  'dot-circle': 'circle-dot',
  'drafting-compass': 'compass-drafting',
  'dribbble-square': 'square-dribbble',
  'drivers-license': 'id-card',
  earth: 'earth-americas',
  'earth-america': 'earth-americas',
  edit: 'pen-to-square',
  'ellipsis-h': 'ellipsis',
  'ellipsis-v': 'ellipsis-vertical',
  'envelope-square': 'square-envelope',
  eur: 'euro-sign',
  euro: 'euro-sign',
  exchange: 'arrow-right-arrow-left',
  'exchange-alt': 'right-left',
  'exclamation-circle': 'circle-exclamation',
  'exclamation-triangle': 'triangle-exclamation',
  'expand-alt': 'up-right-and-down-left-from-center',
  'expand-arrows-alt': 'maximize',
  'external-link': 'arrow-up-right-from-square',
  'external-link-alt': 'up-right-from-square',
  'external-link-square': 'square-arrow-up-right',
  'external-link-square-alt': 'square-up-right',
  'eye-dropper-empty': 'eye-dropper',
  eyedropper: 'eye-dropper',
  'facebook-square': 'square-facebook',
  'fast-backward': 'backward-fast',
  'fast-forward': 'forward-fast',
  'feather-alt': 'feather-pointed',
  feed: 'rss',
  female: 'person-dress',
  'fighter-jet': 'jet-fighter',
  'file-alt': 'file-lines',
  'file-archive': 'file-zipper',
  'file-clipboard': 'paste',
  'file-download': 'file-arrow-down',
  'file-edit': 'file-pen',
  'file-medical-alt': 'file-waveform',
  'file-text': 'file-lines',
  'file-upload': 'file-arrow-up',
  'fire-alt': 'fire-flame-curved',
  'first-aid': 'kit-medical',
  'fist-raised': 'hand-fist',
  flushed: 'face-flushed',
  'folder-blank': 'folder',
  'font-awesome-alt': 'square-font-awesome-stroke',
  'font-awesome-flag': 'font-awesome',
  'font-awesome-logo-full': 'font-awesome',
  'football-ball': 'football',
  frown: 'face-frown',
  'frown-open': 'face-frown-open',
  'funnel-dollar': 'filter-circle-dollar',
  'futbol-ball': 'futbol',
  'gauge-med': 'gauge',
  'gauge-simple-med': 'gauge-simple',
  gbp: 'sterling-sign',
  'git-square': 'square-git',
  'github-square': 'square-github',
  'gitlab-square': 'square-gitlab',
  'glass-cheers': 'champagne-glasses',
  'glass-martini': 'martini-glass-empty',
  'glass-martini-alt': 'martini-glass',
  'glass-whiskey': 'whiskey-glass',
  'globe-africa': 'earth-africa',
  'globe-americas': 'earth-americas',
  'globe-asia': 'earth-asia',
  'globe-europe': 'earth-europe',
  'globe-oceania': 'earth-oceania',
  'golf-ball': 'golf-ball-tee',
  'google-plus-square': 'square-google-plus',
  grimace: 'face-grimace',
  grin: 'face-grin',
  'grin-alt': 'face-grin-wide',
  'grin-beam': 'face-grin-beam',
  'grin-beam-sweat': 'face-grin-beam-sweat',
  'grin-hearts': 'face-grin-hearts',
  'grin-squint': 'face-grin-squint',
  'grin-squint-tears': 'face-grin-squint-tears',
  'grin-stars': 'face-grin-stars',
  'grin-tears': 'face-grin-tears',
  'grin-tongue': 'face-grin-tongue',
  'grin-tongue-squint': 'face-grin-tongue-squint',
  'grin-tongue-wink': 'face-grin-tongue-wink',
  'grin-wink': 'face-grin-wink',
  'grip-horizontal': 'grip',
  'h-square': 'square-h',
  'hacker-news-square': 'square-hacker-news',
  hamburger: 'burger',
  'hand-holding-usd': 'hand-holding-dollar',
  'hand-holding-water': 'hand-holding-droplet',
  'hand-paper': 'hand',
  'hand-rock': 'hand-back-fist',
  'hands-american-sign-language-interpreting': 'hands-asl-interpreting',
  'hands-helping': 'handshake-angle',
  'hands-wash': 'hands-bubbles',
  'handshake-alt': 'handshake-simple',
  'handshake-alt-slash': 'handshake-simple-slash',
  'hard-hat': 'helmet-safety',
  'hard-of-hearing': 'ear-deaf',
  'hat-hard': 'helmet-safety',
  haykal: 'bahai',
  hdd: 'hard-drive',
  header: 'heading',
  'headphones-alt': 'headphones-simple',
  'heart-broken': 'heart-crack',
  'heart-music-camera-bolt': 'icons',
  heartbeat: 'heart-pulse',
  hiking: 'person-hiking',
  history: 'clock-rotate-left',
  home: 'house',
  'home-alt': 'house',
  'home-lg': 'house-chimney',
  'home-lg-alt': 'house',
  'home-user': 'house-user',
  'hospital-alt': 'hospital',
  'hospital-symbol': 'circle-h',
  'hospital-wide': 'hospital',
  'hot-tub': 'hot-tub-person',
  'hourglass-1': 'hourglass-start',
  'hourglass-2': 'hourglass-half',
  'hourglass-3': 'hourglass-end',
  'hourglass-empty': 'hourglass',
  'house-damage': 'house-chimney-crack',
  hryvnia: 'hryvnia-sign',
  'id-card-alt': 'id-card-clip',
  ils: 'shekel-sign',
  'indian-rupee': 'indian-rupee-sign',
  'info-circle': 'circle-info',
  innosoft: '42-group',
  inr: 'indian-rupee-sign',
  'instagram-square': 'square-instagram',
  institution: 'building-columns',
  'journal-whills': 'book-journal-whills',
  jpy: 'yen-sign',
  'js-square': 'square-js',
  kiss: 'face-kiss',
  'kiss-beam': 'face-kiss-beam',
  'kiss-wink-heart': 'face-kiss-wink-heart',
  krw: 'won-sign',
  'ladder-water': 'water-ladder',
  'landmark-alt': 'landmark-dome',
  'laptop-house': 'house-laptop',
  'lastfm-square': 'square-lastfm',
  laugh: 'face-laugh',
  'laugh-beam': 'face-laugh-beam',
  'laugh-squint': 'face-laugh-squint',
  'laugh-wink': 'face-laugh-wink',
  legal: 'gavel',
  'level-down': 'arrow-turn-down',
  'level-down-alt': 'turn-down',
  'level-up': 'arrow-turn-up',
  'level-up-alt': 'turn-up',
  'line-chart': 'chart-line',
  'list-1-2': 'list-ol',
  'list-alt': 'rectangle-list',
  'list-dots': 'list-ul',
  'list-numeric': 'list-ol',
  'list-squares': 'list',
  location: 'location-crosshairs',
  'long-arrow-alt-down': 'down-long',
  'long-arrow-alt-left': 'left-long',
  'long-arrow-alt-right': 'right-long',
  'long-arrow-alt-up': 'up-long',
  'long-arrow-down': 'arrow-down-long',
  'long-arrow-left': 'arrow-left-long',
  'long-arrow-right': 'arrow-right-long',
  'long-arrow-up': 'arrow-up-long',
  'low-vision': 'eye-low-vision',
  'luggage-cart': 'cart-flatbed-suitcase',
  magic: 'wand-magic',
  'magic-wand-sparkles': 'wand-magic-sparkles',
  'mail-bulk': 'envelopes-bulk',
  'mail-forward': 'share',
  'mail-reply': 'reply',
  'mail-reply-all': 'reply-all',
  male: 'person',
  'map-marked': 'map-location',
  'map-marked-alt': 'map-location-dot',
  'map-marker': 'location-pin',
  'map-marker-alt': 'location-dot',
  'map-signs': 'signs-post',
  'mars-stroke-h': 'mars-stroke-right',
  'mars-stroke-v': 'mars-stroke-up',
  'medium-m': 'medium',
  medkit: 'suitcase-medical',
  meh: 'face-meh',
  'meh-blank': 'face-meh-blank',
  'meh-rolling-eyes': 'face-rolling-eyes',
  'microphone-alt': 'microphone-lines',
  'microphone-alt-slash': 'microphone-lines-slash',
  'minus-circle': 'circle-minus',
  'minus-square': 'square-minus',
  'mobile-alt': 'mobile-screen-button',
  'mobile-android': 'mobile',
  'mobile-android-alt': 'mobile-screen',
  'mobile-phone': 'mobile',
  'money-bill-alt': 'money-bill-1',
  'money-bill-wave-alt': 'money-bill-1-wave',
  'money-check-alt': 'money-check-dollar',
  'mortar-board': 'graduation-cap',
  mouse: 'computer-mouse',
  'mouse-pointer': 'arrow-pointer',
  multiply: 'xmark',
  museum: 'building-columns',
  navicon: 'bars',
  'odnoklassniki-square': 'square-odnoklassniki',
  'paint-brush': 'paintbrush',
  parking: 'square-parking',
  pastafarianism: 'spaghetti-monster-flying',
  'pause-circle': 'circle-pause',
  'pen-alt': 'pen-clip',
  'pen-square': 'square-pen',
  'pencil-alt': 'pencil',
  'pencil-ruler': 'pen-ruler',
  'pencil-square': 'square-pen',
  'people-arrows-left-right': 'people-arrows',
  'people-carry': 'people-carry-box',
  percentage: 'percent',
  'phone-alt': 'phone-flip',
  'phone-square': 'square-phone',
  'phone-square-alt': 'square-phone-flip',
  'photo-video': 'photo-film',
  'pie-chart': 'chart-pie',
  'pied-piper-square': 'square-pied-piper',
  'ping-pong-paddle-ball': 'table-tennis-paddle-ball',
  'pinterest-square': 'square-pinterest',
  'play-circle': 'circle-play',
  'plus-circle': 'circle-plus',
  'plus-square': 'square-plus',
  poll: 'square-poll-vertical',
  'poll-h': 'square-poll-horizontal',
  'poo-bolt': 'poo-storm',
  portrait: 'image-portrait',
  'pound-sign': 'sterling-sign',
  pray: 'person-praying',
  'praying-hands': 'hands-praying',
  'prescription-bottle-alt': 'prescription-bottle-medical',
  procedures: 'bed-pulse',
  'project-diagram': 'diagram-project',
  'question-circle': 'circle-question',
  quidditch: 'broom-ball',
  'quidditch-broom-ball': 'broom-ball',
  'quote-left-alt': 'quote-left',
  'quote-right-alt': 'quote-right',
  quran: 'book-quran',
  'radiation-alt': 'circle-radiation',
  random: 'shuffle',
  'rectangle-times': 'rectangle-xmark',
  'reddit-square': 'square-reddit',
  redo: 'arrow-rotate-right',
  'redo-alt': 'rotate-right',
  refresh: 'arrows-rotate',
  remove: 'xmark',
  'remove-format': 'text-slash',
  rendact: 'wpressr',
  reorder: 'bars-staggered',
  rmb: 'yen-sign',
  'rod-asclepius': 'staff-snake',
  'rod-snake': 'staff-snake',
  'rotate-back': 'rotate-left',
  'rotate-backward': 'rotate-left',
  'rotate-forward': 'rotate-right',
  rouble: 'ruble-sign',
  'rss-square': 'square-rss',
  rub: 'ruble-sign',
  ruble: 'ruble-sign',
  running: 'person-running',
  rupee: 'rupee-sign',
  'sad-cry': 'face-sad-cry',
  'sad-tear': 'face-sad-tear',
  save: 'floppy-disk',
  search: 'magnifying-glass',
  'search-dollar': 'magnifying-glass-dollar',
  'search-location': 'magnifying-glass-location',
  'search-minus': 'magnifying-glass-minus',
  'search-plus': 'magnifying-glass-plus',
  'share-alt': 'share-nodes',
  'share-alt-square': 'square-share-nodes',
  'share-square': 'share-from-square',
  shekel: 'shekel-sign',
  sheqel: 'shekel-sign',
  'sheqel-sign': 'shekel-sign',
  'shield-alt': 'shield-halved',
  'shield-blank': 'shield',
  'shipping-fast': 'truck-fast',
  'shopping-bag': 'bag-shopping',
  'shopping-basket': 'basket-shopping',
  'shopping-cart': 'cart-shopping',
  'shuttle-van': 'van-shuttle',
  sign: 'sign-hanging',
  'sign-in': 'arrow-right-to-bracket',
  'sign-in-alt': 'right-to-bracket',
  'sign-language': 'hands',
  'sign-out': 'arrow-right-from-bracket',
  'sign-out-alt': 'right-from-bracket',
  'signal-5': 'signal',
  'signal-perfect': 'signal',
  signing: 'hands',
  skating: 'person-skating',
  skiing: 'person-skiing',
  'skiing-nordic': 'person-skiing-nordic',
  'slack-hash': 'slack',
  'sliders-h': 'sliders',
  smile: 'face-smile',
  'smile-beam': 'face-smile-beam',
  'smile-wink': 'face-smile-wink',
  'smoking-ban': 'ban-smoking',
  sms: 'comment-sms',
  'snapchat-ghost': 'snapchat',
  'snapchat-square': 'square-snapchat',
  snowboarding: 'person-snowboarding',
  'soccer-ball': 'futbol',
  'sort-alpha-asc': 'arrow-down-a-z',
  'sort-alpha-desc': 'arrow-down-z-a',
  'sort-alpha-down': 'arrow-down-a-z',
  'sort-alpha-down-alt': 'arrow-down-z-a',
  'sort-alpha-up': 'arrow-up-a-z',
  'sort-alpha-up-alt': 'arrow-up-z-a',
  'sort-amount-asc': 'arrow-down-wide-short',
  'sort-amount-desc': 'arrow-down-short-wide',
  'sort-amount-down': 'arrow-down-wide-short',
  'sort-amount-down-alt': 'arrow-down-short-wide',
  'sort-amount-up': 'arrow-up-wide-short',
  'sort-amount-up-alt': 'arrow-up-short-wide',
  'sort-asc': 'sort-up',
  'sort-desc': 'sort-down',
  'sort-numeric-asc': 'arrow-down-1-9',
  'sort-numeric-desc': 'arrow-down-9-1',
  'sort-numeric-down': 'arrow-down-1-9',
  'sort-numeric-down-alt': 'arrow-down-9-1',
  'sort-numeric-up': 'arrow-up-1-9',
  'sort-numeric-up-alt': 'arrow-up-9-1',
  'space-shuttle': 'shuttle-space',
  sprout: 'seedling',
  'square-kickstarter': 'kickstarter',
  'square-root-alt': 'square-root-variable',
  'staff-aesculapius': 'staff-snake',
  'star-half-alt': 'star-half-stroke',
  'steam-square': 'square-steam',
  'step-backward': 'backward-step',
  'step-forward': 'forward-step',
  'sticky-note': 'note-sticky',
  'stop-circle': 'circle-stop',
  'store-alt': 'shop',
  'store-alt-slash': 'shop-slash',
  stream: 'bars-staggered',
  subtract: 'minus',
  subway: 'train-subway',
  surprise: 'face-surprise',
  swimmer: 'person-swimming',
  'swimming-pool': 'water-ladder',
  sync: 'arrows-rotate',
  'sync-alt': 'rotate',
  't-shirt': 'shirt',
  'table-tennis': 'table-tennis-paddle-ball',
  'tablet-alt': 'tablet-screen-button',
  'tablet-android': 'tablet',
  tachometer: 'gauge-simple-high',
  'tachometer-alt': 'gauge-high',
  'tachometer-alt-average': 'gauge',
  'tachometer-alt-fast': 'gauge-high',
  'tachometer-average': 'gauge-simple',
  'tachometer-fast': 'gauge-simple-high',
  tanakh: 'book-tanakh',
  tasks: 'list-check',
  'tasks-alt': 'bars-progress',
  'telegram-plane': 'telegram',
  teletype: 'tty',
  television: 'tv',
  'temperature-0': 'temperature-empty',
  'temperature-1': 'temperature-quarter',
  'temperature-2': 'temperature-half',
  'temperature-3': 'temperature-three-quarters',
  'temperature-4': 'temperature-full',
  'temperature-down': 'temperature-arrow-down',
  'temperature-up': 'temperature-arrow-up',
  tenge: 'tenge-sign',
  th: 'table-cells',
  'th-large': 'table-cells-large',
  'th-list': 'table-list',
  'theater-masks': 'masks-theater',
  'thermometer-0': 'temperature-empty',
  'thermometer-1': 'temperature-quarter',
  'thermometer-2': 'temperature-half',
  'thermometer-3': 'temperature-three-quarters',
  'thermometer-4': 'temperature-full',
  'thermometer-empty': 'temperature-empty',
  'thermometer-full': 'temperature-full',
  'thermometer-half': 'temperature-half',
  'thermometer-quarter': 'temperature-quarter',
  'thermometer-three-quarters': 'temperature-three-quarters',
  'thumb-tack': 'thumbtack',
  'thumb-tack-slash': 'thumbtack-slash',
  thunderstorm: 'cloud-bolt',
  'ticket-alt': 'ticket-simple',
  times: 'xmark',
  'times-circle': 'circle-xmark',
  'times-rectangle': 'rectangle-xmark',
  'times-square': 'square-xmark',
  tint: 'droplet',
  'tint-slash': 'droplet-slash',
  tired: 'face-tired',
  tools: 'screwdriver-wrench',
  torah: 'scroll-torah',
  tram: 'cable-car',
  'transgender-alt': 'transgender',
  'trash-alt': 'trash-can',
  'trash-restore': 'trash-arrow-up',
  'trash-restore-alt': 'trash-can-arrow-up',
  'triangle-circle-square': 'shapes',
  'truck-loading': 'truck-ramp-box',
  try: 'turkish-lira-sign',
  tshirt: 'shirt',
  'tumblr-square': 'square-tumblr',
  'turkish-lira': 'turkish-lira-sign',
  'tv-alt': 'tv',
  'twitter-square': 'square-twitter',
  undo: 'arrow-rotate-left',
  'undo-alt': 'rotate-left',
  university: 'building-columns',
  unlink: 'link-slash',
  'unlock-alt': 'unlock-keyhole',
  unsorted: 'sort',
  usd: 'dollar-sign',
  'user-alt': 'user-large',
  'user-alt-slash': 'user-large-slash',
  'user-circle': 'circle-user',
  'user-cog': 'user-gear',
  'user-edit': 'user-pen',
  'user-friends': 'user-group',
  'user-md': 'user-doctor',
  'user-times': 'user-xmark',
  'users-cog': 'users-gear',
  'utensil-spoon': 'spoon',
  vcard: 'address-card',
  'viadeo-square': 'square-viadeo',
  'video-camera': 'video',
  'vimeo-square': 'square-vimeo',
  'volleyball-ball': 'volleyball',
  'volume-control-phone': 'phone-volume',
  'volume-down': 'volume-low',
  'volume-mute': 'volume-xmark',
  'volume-times': 'volume-xmark',
  'volume-up': 'volume-high',
  'vote-yea': 'check-to-slot',
  walking: 'person-walking',
  warning: 'triangle-exclamation',
  weight: 'weight-scale',
  'whatsapp-square': 'square-whatsapp',
  'wheat-alt': 'wheat-awn',
  'wheelchair-alt': 'wheelchair-move',
  'wifi-3': 'wifi',
  'wifi-strong': 'wifi',
  'window-close': 'rectangle-xmark',
  'wine-glass-alt': 'wine-glass-empty',
  won: 'won-sign',
  wsh: 'wirsindhandwerk',
  'xing-square': 'square-xing',
  'xmark-circle': 'circle-xmark',
  'xmark-square': 'square-xmark',
  yen: 'yen-sign',
  'youtube-square': 'square-youtube',
  zap: 'bolt',
};

/**
 * The names of the icons in the free Font Awesome set, without aliases.
 */
export const fontAwesomeIconNames = new Set<string>([
  '0',
  '1',
  '2',
  '3',
  '4',
  '42-group',
  '5',
  '500px',
  '6',
  '7',
  '8',
  '9',
  'a',
  'accessible-icon',
  'accusoft',
  'address-book',
  'address-card',
  'adn',
  'adversal',
  'affiliatetheme',
  'airbnb',
  'algolia',
  'align-center',
  'align-justify',
  'align-left',
  'align-right',
  'alipay',
  'amazon',
  'amazon-pay',
  'amilia',
  'anchor',
  'anchor-circle-check',
  'anchor-circle-exclamation',
  'anchor-circle-xmark',
  'anchor-lock',
  'android',
  'angellist',
  'angle-down',
  'angle-left',
  'angle-right',
  'angle-up',
  'angles-down',
  'angles-left',
  'angles-right',
  'angles-up',
  'angrycreative',
  'angular',
  'ankh',
  'app-store',
  'app-store-ios',
  'apper',
  'apple',
  'apple-pay',
  'apple-whole',
  'archway',
  'arrow-down',
  'arrow-down-1-9',
  'arrow-down-9-1',
  'arrow-down-a-z',
  'arrow-down-long',
  'arrow-down-short-wide',
  'arrow-down-up-across-line',
  'arrow-down-up-lock',
  'arrow-down-wide-short',
  'arrow-down-z-a',
  'arrow-left',
  'arrow-left-long',
  'arrow-pointer',
  'arrow-right',
  'arrow-right-arrow-left',
  'arrow-right-from-bracket',
  'arrow-right-long',
  'arrow-right-to-bracket',
  'arrow-right-to-city',
  'arrow-rotate-left',
  'arrow-rotate-right',
  'arrow-trend-down',
  'arrow-trend-up',
  'arrow-turn-down',
  'arrow-turn-up',
  'arrow-up',
  'arrow-up-1-9',
  'arrow-up-9-1',
  'arrow-up-a-z',
  'arrow-up-from-bracket',
  'arrow-up-from-ground-water',
  'arrow-up-from-water-pump',
  'arrow-up-long',
  'arrow-up-right-dots',
  'arrow-up-right-from-square',
  'arrow-up-short-wide',
  'arrow-up-wide-short',
  'arrow-up-z-a',
  'arrows-down-to-line',
  'arrows-down-to-people',
  'arrows-left-right',
  'arrows-left-right-to-line',
  'arrows-rotate',
  'arrows-spin',
  'arrows-split-up-and-left',
  'arrows-to-circle',
  'arrows-to-dot',
  'arrows-to-eye',
  'arrows-turn-right',
  'arrows-turn-to-dots',
  'arrows-up-down',
  'arrows-up-down-left-right',
  'arrows-up-to-line',
  'artstation',
  'asterisk',
  'asymmetrik',
  'at',
  'atlassian',
  'atom',
  'audible',
  'audio-description',
  'austral-sign',
  'autoprefixer',
  'avianex',
  'aviato',
  'award',
  'aws',
  'b',
  'baby',
  'baby-carriage',
  'backward',
  'backward-fast',
  'backward-step',
  'bacon',
  'bacteria',
  'bacterium',
  'bag-shopping',
  'bahai',
  'baht-sign',
  'ban',
  'ban-smoking',
  'bandage',
  'bandcamp',
  'bangladeshi-taka-sign',
  'barcode',
  'bars',
  'bars-progress',
  'bars-staggered',
  'baseball',
  'baseball-bat-ball',
  'basket-shopping',
  'basketball',
  'bath',
  'battery-empty',
  'battery-full',
  'battery-half',
  'battery-quarter',
  'battery-three-quarters',
  'battle-net',
  'bed',
  'bed-pulse',
  'beer-mug-empty',
  'behance',
  'bell',
  'bell-concierge',
  'bell-slash',
  'bezier-curve',
  'bicycle',
  'bilibili',
  'bimobject',
  'binoculars',
  'biohazard',
  'bitbucket',
  'bitcoin',
  'bitcoin-sign',
  'bity',
  'black-tie',
  'blackberry',
  'blender',
  'blender-phone',
  'blog',
  'blogger',
  'blogger-b',
  'bluesky',
  'bluetooth',
  'bluetooth-b',
  'bold',
  'bolt',
  'bolt-lightning',
  'bomb',
  'bone',
  'bong',
  'book',
  'book-atlas',
  'book-bible',
  'book-bookmark',
  'book-journal-whills',
  'book-medical',
  'book-open',
  'book-open-reader',
  'book-quran',
  'book-skull',
  'book-tanakh',
  'bookmark',
  'bootstrap',
  'border-all',
  'border-none',
  'border-top-left',
  'bore-hole',
  'bots',
  'bottle-droplet',
  'bottle-water',
  'bowl-food',
  'bowl-rice',
  'bowling-ball',
  'box',
  'box-archive',
  'box-open',
  'box-tissue',
  'boxes-packing',
  'boxes-stacked',
  'braille',
  'brain',
  'brave',
  'brave-reverse',
  'brazilian-real-sign',
  'bread-slice',
  'bridge',
  'bridge-circle-check',
  'bridge-circle-exclamation',
  'bridge-circle-xmark',
  'bridge-lock',
  'bridge-water',
  'briefcase',
  'briefcase-medical',
  'broom',
  'broom-ball',
  'brush',
  'btc',
  'bucket',
  'buffer',
  'bug',
  'bug-slash',
  'bugs',
  'building',
  'building-circle-arrow-right',
  'building-circle-check',
  'building-circle-exclamation',
  'building-circle-xmark',
  'building-columns',
  'building-flag',
  'building-lock',
  'building-ngo',
  'building-shield',
  'building-un',
  'building-user',
  'building-wheat',
  'bullhorn',
  'bullseye',
  'burger',
  'buromobelexperte',
  'burst',
  'bus',
  'bus-simple',
  'business-time',
  'buy-n-large',
  'buysellads',
  'c',
  'cable-car',
  'cake-candles',
  'calculator',
  'calendar',
  'calendar-check',
  'calendar-day',
  'calendar-days',
  'calendar-minus',
  'calendar-plus',
  'calendar-week',
  'calendar-xmark',
  'camera',
  'camera-retro',
  'camera-rotate',
  'campground',
  'canadian-maple-leaf',
  'candy-cane',
  'cannabis',
  'capsules',
  'car',
  'car-battery',
  'car-burst',
  'car-on',
  'car-rear',
  'car-side',
  'car-tunnel',
  'caravan',
  'caret-down',
  'caret-left',
  'caret-right',
  'caret-up',
  'carrot',
  'cart-arrow-down',
  'cart-flatbed',
  'cart-flatbed-suitcase',
  'cart-plus',
  'cart-shopping',
  'cash-register',
  'cat',
  'cc-amazon-pay',
  'cc-amex',
  'cc-apple-pay',
  'cc-diners-club',
  'cc-discover',
  'cc-jcb',
  'cc-mastercard',
  'cc-paypal',
  'cc-stripe',
  'cc-visa',
  'cedi-sign',
  'cent-sign',
  'centercode',
  'centos',
  'certificate',
  'chair',
  'chalkboard',
  'chalkboard-user',
  'champagne-glasses',
  'charging-station',
  'chart-area',
  'chart-bar',
  'chart-column',
  'chart-diagram',
  'chart-gantt',
  'chart-line',
  'chart-pie',
  'chart-simple',
  'check',
  'check-double',
  'check-to-slot',
  'cheese',
  'chess',
  'chess-bishop',
  'chess-board',
  'chess-king',
  'chess-knight',
  'chess-pawn',
  'chess-queen',
  'chess-rook',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'child',
  'child-combatant',
  'child-dress',
  'child-reaching',
  'children',
  'chrome',
  'chromecast',
  'church',
  'circle',
  'circle-arrow-down',
  'circle-arrow-left',
  'circle-arrow-right',
  'circle-arrow-up',
  'circle-check',
  'circle-chevron-down',
  'circle-chevron-left',
  'circle-chevron-right',
  'circle-chevron-up',
  'circle-dollar-to-slot',
  'circle-dot',
  'circle-down',
  'circle-exclamation',
  'circle-h',
  'circle-half-stroke',
  'circle-info',
  'circle-left',
  'circle-minus',
  'circle-nodes',
  'circle-notch',
  'circle-pause',
  'circle-play',
  'circle-plus',
  'circle-question',
  'circle-radiation',
  'circle-right',
  'circle-stop',
  'circle-up',
  'circle-user',
  'circle-xmark',
  'city',
  'clapperboard',
  'clipboard',
  'clipboard-check',
  'clipboard-list',
  'clipboard-question',
  'clipboard-user',
  'clock',
  'clock-rotate-left',
  'clone',
  'closed-captioning',
  'cloud',
  'cloud-arrow-down',
  'cloud-arrow-up',
  'cloud-bolt',
  'cloud-meatball',
  'cloud-moon',
  'cloud-moon-rain',
  'cloud-rain',
  'cloud-showers-heavy',
  'cloud-showers-water',
  'cloud-sun',
  'cloud-sun-rain',
  'cloudflare',
  'cloudscale',
  'cloudsmith',
  'cloudversify',
  'clover',
  'cmplid',
  'code',
  'code-branch',
  'code-commit',
  'code-compare',
  'code-fork',
  'code-merge',
  'code-pull-request',
  'codepen',
  'codiepie',
  'coins',
  'colon-sign',
  'comment',
  'comment-dollar',
  'comment-dots',
  'comment-medical',
  'comment-nodes',
  'comment-slash',
  'comment-sms',
  'comments',
  'comments-dollar',
  'compact-disc',
  'compass',
  'compass-drafting',
  'compress',
  'computer',
  'computer-mouse',
  'confluence',
  'connectdevelop',
  'contao',
  'cookie',
  'cookie-bite',
  'copy',
  'copyright',
  'cotton-bureau',
  'couch',
  'cow',
  'cpanel',
  'creative-commons',
  'creative-commons-by',
  'creative-commons-nc',
  'creative-commons-nc-eu',
  'creative-commons-nc-jp',
  'creative-commons-nd',
  'creative-commons-pd',
  'creative-commons-pd-alt',
  'creative-commons-remix',
  'creative-commons-sa',
  'creative-commons-sampling',
  'creative-commons-sampling-plus',
  'creative-commons-share',
  'creative-commons-zero',
  'credit-card',
  'critical-role',
  'crop',
  'crop-simple',
  'cross',
  'crosshairs',
  'crow',
  'crown',
  'crutch',
  'cruzeiro-sign',
  'css',
  'css3',
  'css3-alt',
  'cube',
  'cubes',
  'cubes-stacked',
  'cuttlefish',
  'd',
  'd-and-d',
  'd-and-d-beyond',
  'dailymotion',
  'dart-lang',
  'dashcube',
  'database',
  'debian',
  'deezer',
  'delete-left',
  'delicious',
  'democrat',
  'deploydog',
  'deskpro',
  'desktop',
  'dev',
  'deviantart',
  'dharmachakra',
  'dhl',
  'diagram-next',
  'diagram-predecessor',
  'diagram-project',
  'diagram-successor',
  'diamond',
  'diamond-turn-right',
  'diaspora',
  'dice',
  'dice-d20',
  'dice-d6',
  'dice-five',
  'dice-four',
  'dice-one',
  'dice-six',
  'dice-three',
  'dice-two',
  'digg',
  'digital-ocean',
  'discord',
  'discourse',
  'disease',
  'display',
  'divide',
  'dna',
  'dochub',
  'docker',
  'dog',
  'dollar-sign',
  'dolly',
  'dong-sign',
  'door-closed',
  'door-open',
  'dove',
  'down-left-and-up-right-to-center',
  'down-long',
  'download',
  'draft2digital',
  'dragon',
  'draw-polygon',
  'dribbble',
  'dropbox',
  'droplet',
  'droplet-slash',
  'drum',
  'drum-steelpan',
  'drumstick-bite',
  'drupal',
  'dumbbell',
  'dumpster',
  'dumpster-fire',
  'dungeon',
  'dyalog',
  'e',
  'ear-deaf',
  'ear-listen',
  'earlybirds',
  'earth-africa',
  'earth-americas',
  'earth-asia',
  'earth-europe',
  'earth-oceania',
  'ebay',
  'edge',
  'edge-legacy',
  'egg',
  'eject',
  'elementor',
  'elevator',
  'ellipsis',
  'ellipsis-vertical',
  'ello',
  'ember',
  'empire',
  'envelope',
  'envelope-circle-check',
  'envelope-open',
  'envelope-open-text',
  'envelopes-bulk',
  'envira',
  'equals',
  'eraser',
  'erlang',
  'ethereum',
  'ethernet',
  'etsy',
  'euro-sign',
  'evernote',
  'exclamation',
  'expand',
  'expeditedssl',
  'explosion',
  'eye',
  'eye-dropper',
  'eye-low-vision',
  'eye-slash',
  'f',
  'face-angry',
  'face-dizzy',
  'face-flushed',
  'face-frown',
  'face-frown-open',
  'face-grimace',
  'face-grin',
  'face-grin-beam',
  'face-grin-beam-sweat',
  'face-grin-hearts',
  'face-grin-squint',
  'face-grin-squint-tears',
  'face-grin-stars',
  'face-grin-tears',
  'face-grin-tongue',
  'face-grin-tongue-squint',
  'face-grin-tongue-wink',
  'face-grin-wide',
  'face-grin-wink',
  'face-kiss',
  'face-kiss-beam',
  'face-kiss-wink-heart',
  'face-laugh',
  'face-laugh-beam',
  'face-laugh-squint',
  'face-laugh-wink',
  'face-meh',
  'face-meh-blank',
  'face-rolling-eyes',
  'face-sad-cry',
  'face-sad-tear',
  'face-smile',
  'face-smile-beam',
  'face-smile-wink',
  'face-surprise',
  'face-tired',
  'facebook',
  'facebook-f',
  'facebook-messenger',
  'fan',
  'fantasy-flight-games',
  'faucet',
  'faucet-drip',
  'fax',
  'feather',
  'feather-pointed',
  'fedex',
  'fedora',
  'ferry',
  'figma',
  'file',
  'file-arrow-down',
  'file-arrow-up',
  'file-audio',
  'file-circle-check',
  'file-circle-exclamation',
  'file-circle-minus',
  'file-circle-plus',
  'file-circle-question',
  'file-circle-xmark',
  'file-code',
  'file-contract',
  'file-csv',
  'file-excel',
  'file-export',
  'file-fragment',
  'file-half-dashed',
  'file-image',
  'file-import',
  'file-invoice',
  'file-invoice-dollar',
  'file-lines',
  'file-medical',
  'file-pdf',
  'file-pen',
  'file-powerpoint',
  'file-prescription',
  'file-shield',
  'file-signature',
  'file-video',
  'file-waveform',
  'file-word',
  'file-zipper',
  'files-pinwheel',
  'fill',
  'fill-drip',
  'film',
  'filter',
  'filter-circle-dollar',
  'filter-circle-xmark',
  'fingerprint',
  'fire',
  'fire-burner',
  'fire-extinguisher',
  'fire-flame-curved',
  'fire-flame-simple',
  'firefox',
  'firefox-browser',
  'first-order',
  'first-order-alt',
  'firstdraft',
  'fish',
  'fish-fins',
  'flag',
  'flag-checkered',
  'flag-usa',
  'flask',
  'flask-vial',
  'flickr',
  'flipboard',
  'floppy-disk',
  'florin-sign',
  'flutter',
  'fly',
  'folder',
  'folder-closed',
  'folder-minus',
  'folder-open',
  'folder-plus',
  'folder-tree',
  'font',
  'font-awesome',
  'fonticons',
  'fonticons-fi',
  'football',
  'fort-awesome',
  'fort-awesome-alt',
  'forumbee',
  'forward',
  'forward-fast',
  'forward-step',
  'foursquare',
  'franc-sign',
  'free-code-camp',
  'freebsd',
  'frog',
  'fulcrum',
  'futbol',
  'g',
  'galactic-republic',
  'galactic-senate',
  'gamepad',
  'gas-pump',
  'gauge',
  'gauge-high',
  'gauge-simple',
  'gauge-simple-high',
  'gavel',
  'gear',
  'gears',
  'gem',
  'genderless',
  'get-pocket',
  'gg',
  'gg-circle',
  'ghost',
  'gift',
  'gifts',
  'git',
  'git-alt',
  'github',
  'github-alt',
  'gitkraken',
  'gitlab',
  'gitter',
  'glass-water',
  'glass-water-droplet',
  'glasses',
  'glide',
  'glide-g',
  'globe',
  'gofore',
  'golang',
  'golf-ball-tee',
  'goodreads',
  'goodreads-g',
  'google',
  'google-drive',
  'google-pay',
  'google-play',
  'google-plus',
  'google-plus-g',
  'google-scholar',
  'google-wallet',
  'gopuram',
  'graduation-cap',
  'gratipay',
  'grav',
  'greater-than',
  'greater-than-equal',
  'grip',
  'grip-lines',
  'grip-lines-vertical',
  'grip-vertical',
  'gripfire',
  'group-arrows-rotate',
  'grunt',
  'guarani-sign',
  'guilded',
  'guitar',
  'gulp',
  'gun',
  'h',
  'hacker-news',
  'hackerrank',
  'hammer',
  'hamsa',
  'hand',
  'hand-back-fist',
  'hand-dots',
  'hand-fist',
  'hand-holding',
  'hand-holding-dollar',
  'hand-holding-droplet',
  'hand-holding-hand',
  'hand-holding-heart',
  'hand-holding-medical',
  'hand-lizard',
  'hand-middle-finger',
  'hand-peace',
  'hand-point-down',
  'hand-point-left',
  'hand-point-right',
  'hand-point-up',
  'hand-pointer',
  'hand-scissors',
  'hand-sparkles',
  'hand-spock',
  'handcuffs',
  'hands',
  'hands-asl-interpreting',
  'hands-bound',
  'hands-bubbles',
  'hands-clapping',
  'hands-holding',
  'hands-holding-child',
  'hands-holding-circle',
  'hands-praying',
  'handshake',
  'handshake-angle',
  'handshake-simple',
  'handshake-simple-slash',
  'handshake-slash',
  'hanukiah',
  'hard-drive',
  'hashnode',
  'hashtag',
  'hat-cowboy',
  'hat-cowboy-side',
  'hat-wizard',
  'head-side-cough',
  'head-side-cough-slash',
  'head-side-mask',
  'head-side-virus',
  'heading',
  'headphones',
  'headphones-simple',
  'headset',
  'heart',
  'heart-circle-bolt',
  'heart-circle-check',
  'heart-circle-exclamation',
  'heart-circle-minus',
  'heart-circle-plus',
  'heart-circle-xmark',
  'heart-crack',
  'heart-pulse',
  'helicopter',
  'helicopter-symbol',
  'helmet-safety',
  'helmet-un',
  'hexagon-nodes',
  'hexagon-nodes-bolt',
  'highlighter',
  'hill-avalanche',
  'hill-rockslide',
  'hippo',
  'hips',
  'hire-a-helper',
  'hive',
  'hockey-puck',
  'holly-berry',
  'hooli',
  'hornbill',
  'horse',
  'horse-head',
  'hospital',
  'hospital-user',
  'hot-tub-person',
  'hotdog',
  'hotel',
  'hotjar',
  'hourglass',
  'hourglass-end',
  'hourglass-half',
  'hourglass-start',
  'house',
  'house-chimney',
  'house-chimney-crack',
  'house-chimney-medical',
  'house-chimney-user',
  'house-chimney-window',
  'house-circle-check',
  'house-circle-exclamation',
  'house-circle-xmark',
  'house-crack',
  'house-fire',
  'house-flag',
  'house-flood-water',
  'house-flood-water-circle-arrow-right',
  'house-laptop',
  'house-lock',
  'house-medical',
  'house-medical-circle-check',
  'house-medical-circle-exclamation',
  'house-medical-circle-xmark',
  'house-medical-flag',
  'house-signal',
  'house-tsunami',
  'house-user',
  'houzz',
  'hryvnia-sign',
  'html5',
  'hubspot',
  'hurricane',
  'i',
  'i-cursor',
  'ice-cream',
  'icicles',
  'icons',
  'id-badge',
  'id-card',
  'id-card-clip',
  'ideal',
  'igloo',
  'image',
  'image-portrait',
  'images',
  'imdb',
  'inbox',
  'indent',
  'indian-rupee-sign',
  'industry',
  'infinity',
  'info',
  'instagram',
  'instalod',
  'intercom',
  'internet-explorer',
  'invision',
  'ioxhost',
  'italic',
  'itch-io',
  'itunes',
  'itunes-note',
  'j',
  'jar',
  'jar-wheat',
  'java',
  'jedi',
  'jedi-order',
  'jenkins',
  'jet-fighter',
  'jet-fighter-up',
  'jira',
  'joget',
  'joint',
  'joomla',
  'js',
  'jsfiddle',
  'jug-detergent',
  'jxl',
  'k',
  'kaaba',
  'kaggle',
  'key',
  'keybase',
  'keyboard',
  'keycdn',
  'khanda',
  'kickstarter',
  'kickstarter-k',
  'kip-sign',
  'kit-medical',
  'kitchen-set',
  'kiwi-bird',
  'korvue',
  'l',
  'land-mine-on',
  'landmark',
  'landmark-dome',
  'landmark-flag',
  'language',
  'laptop',
  'laptop-code',
  'laptop-file',
  'laptop-medical',
  'laravel',
  'lari-sign',
  'lastfm',
  'layer-group',
  'leaf',
  'leanpub',
  'left-long',
  'left-right',
  'lemon',
  'less',
  'less-than',
  'less-than-equal',
  'letterboxd',
  'life-ring',
  'lightbulb',
  'line',
  'lines-leaning',
  'link',
  'link-slash',
  'linkedin',
  'linkedin-in',
  'linode',
  'linux',
  'lira-sign',
  'list',
  'list-check',
  'list-ol',
  'list-ul',
  'litecoin-sign',
  'location-arrow',
  'location-crosshairs',
  'location-dot',
  'location-pin',
  'location-pin-lock',
  'lock',
  'lock-open',
  'locust',
  'lungs',
  'lungs-virus',
  'lyft',
  'm',
  'magento',
  'magnet',
  'magnifying-glass',
  'magnifying-glass-arrow-right',
  'magnifying-glass-chart',
  'magnifying-glass-dollar',
  'magnifying-glass-location',
  'magnifying-glass-minus',
  'magnifying-glass-plus',
  'mailchimp',
  'manat-sign',
  'mandalorian',
  'map',
  'map-location',
  'map-location-dot',
  'map-pin',
  'markdown',
  'marker',
  'mars',
  'mars-and-venus',
  'mars-and-venus-burst',
  'mars-double',
  'mars-stroke',
  'mars-stroke-right',
  'mars-stroke-up',
  'martini-glass',
  'martini-glass-citrus',
  'martini-glass-empty',
  'mask',
  'mask-face',
  'mask-ventilator',
  'masks-theater',
  'mastodon',
  'mattress-pillow',
  'maxcdn',
  'maximize',
  'mdb',
  'medal',
  'medapps',
  'medium',
  'medrt',
  'meetup',
  'megaport',
  'memory',
  'mendeley',
  'menorah',
  'mercury',
  'message',
  'meta',
  'meteor',
  'microblog',
  'microchip',
  'microphone',
  'microphone-lines',
  'microphone-lines-slash',
  'microphone-slash',
  'microscope',
  'microsoft',
  'mill-sign',
  'minimize',
  'mintbit',
  'minus',
  'mitten',
  'mix',
  'mixcloud',
  'mixer',
  'mizuni',
  'mobile',
  'mobile-button',
  'mobile-retro',
  'mobile-screen',
  'mobile-screen-button',
  'modx',
  'monero',
  'money-bill',
  'money-bill-1',
  'money-bill-1-wave',
  'money-bill-transfer',
  'money-bill-trend-up',
  'money-bill-wave',
  'money-bill-wheat',
  'money-bills',
  'money-check',
  'money-check-dollar',
  'monument',
  'moon',
  'mortar-pestle',
  'mosque',
  'mosquito',
  'mosquito-net',
  'motorcycle',
  'mound',
  'mountain',
  'mountain-city',
  'mountain-sun',
  'mug-hot',
  'mug-saucer',
  'music',
  'n',
  'naira-sign',
  'napster',
  'neos',
  'network-wired',
  'neuter',
  'newspaper',
  'nfc-directional',
  'nfc-symbol',
  'nimblr',
  'node',
  'node-js',
  'not-equal',
  'notdef',
  'note-sticky',
  'notes-medical',
  'npm',
  'ns8',
  'nutritionix',
  'o',
  'object-group',
  'object-ungroup',
  'octopus-deploy',
  'odnoklassniki',
  'odysee',
  'oil-can',
  'oil-well',
  'old-republic',
  'om',
  'opencart',
  'openid',
  'opensuse',
  'opera',
  'optin-monster',
  'orcid',
  'osi',
  'otter',
  'outdent',
  'p',
  'padlet',
  'page4',
  'pagelines',
  'pager',
  'paint-roller',
  'paintbrush',
  'palette',
  'palfed',
  'pallet',
  'panorama',
  'paper-plane',
  'paperclip',
  'parachute-box',
  'paragraph',
  'passport',
  'paste',
  'patreon',
  'pause',
  'paw',
  'paypal',
  'peace',
  'pen',
  'pen-clip',
  'pen-fancy',
  'pen-nib',
  'pen-ruler',
  'pen-to-square',
  'pencil',
  'people-arrows',
  'people-carry-box',
  'people-group',
  'people-line',
  'people-pulling',
  'people-robbery',
  'people-roof',
  'pepper-hot',
  'perbyte',
  'percent',
  'periscope',
  'person',
  'person-arrow-down-to-line',
  'person-arrow-up-from-line',
  'person-biking',
  'person-booth',
  'person-breastfeeding',
  'person-burst',
  'person-cane',
  'person-chalkboard',
  'person-circle-check',
  'person-circle-exclamation',
  'person-circle-minus',
  'person-circle-plus',
  'person-circle-question',
  'person-circle-xmark',
  'person-digging',
  'person-dots-from-line',
  'person-dress',
  'person-dress-burst',
  'person-drowning',
  'person-falling',
  'person-falling-burst',
  'person-half-dress',
  'person-harassing',
  'person-hiking',
  'person-military-pointing',
  'person-military-rifle',
  'person-military-to-person',
  'person-praying',
  'person-pregnant',
  'person-rays',
  'person-rifle',
  'person-running',
  'person-shelter',
  'person-skating',
  'person-skiing',
  'person-skiing-nordic',
  'person-snowboarding',
  'person-swimming',
  'person-through-window',
  'person-walking',
  'person-walking-arrow-loop-left',
  'person-walking-arrow-right',
  'person-walking-dashed-line-arrow-right',
  'person-walking-luggage',
  'person-walking-with-cane',
  'peseta-sign',
  'peso-sign',
  'phabricator',
  'phoenix-framework',
  'phoenix-squadron',
  'phone',
  'phone-flip',
  'phone-slash',
  'phone-volume',
  'photo-film',
  'php',
  'pied-piper',
  'pied-piper-alt',
  'pied-piper-hat',
  'pied-piper-pp',
  'piggy-bank',
  'pills',
  'pinterest',
  'pinterest-p',
  'pix',
  'pixiv',
  'pizza-slice',
  'place-of-worship',
  'plane',
  'plane-arrival',
  'plane-circle-check',
  'plane-circle-exclamation',
  'plane-circle-xmark',
  'plane-departure',
  'plane-lock',
  'plane-slash',
  'plane-up',
  'plant-wilt',
  'plate-wheat',
  'play',
  'playstation',
  'plug',
  'plug-circle-bolt',
  'plug-circle-check',
  'plug-circle-exclamation',
  'plug-circle-minus',
  'plug-circle-plus',
  'plug-circle-xmark',
  'plus',
  'plus-minus',
  'podcast',
  'poo',
  'poo-storm',
  'poop',
  'power-off',
  'prescription',
  'prescription-bottle',
  'prescription-bottle-medical',
  'print',
  'product-hunt',
  'pump-medical',
  'pump-soap',
  'pushed',
  'puzzle-piece',
  'python',
  'q',
  'qq',
  'qrcode',
  'question',
  'quinscape',
  'quora',
  'quote-left',
  'quote-right',
  'r',
  'r-project',
  'radiation',
  'radio',
  'rainbow',
  'ranking-star',
  'raspberry-pi',
  'ravelry',
  'react',
  'reacteurope',
  'readme',
  'rebel',
  'receipt',
  'record-vinyl',
  'rectangle-ad',
  'rectangle-list',
  'rectangle-xmark',
  'recycle',
  'red-river',
  'reddit',
  'reddit-alien',
  'redhat',
  'registered',
  'renren',
  'repeat',
  'reply',
  'reply-all',
  'replyd',
  'republican',
  'researchgate',
  'resolving',
  'restroom',
  'retweet',
  'rev',
  'ribbon',
  'right-from-bracket',
  'right-left',
  'right-long',
  'right-to-bracket',
  'ring',
  'road',
  'road-barrier',
  'road-bridge',
  'road-circle-check',
  'road-circle-exclamation',
  'road-circle-xmark',
  'road-lock',
  'road-spikes',
  'robot',
  'rocket',
  'rocketchat',
  'rockrms',
  'rotate',
  'rotate-left',
  'rotate-right',
  'route',
  'rss',
  'ruble-sign',
  'rug',
  'ruler',
  'ruler-combined',
  'ruler-horizontal',
  'ruler-vertical',
  'rupee-sign',
  'rupiah-sign',
  'rust',
  's',
  'sack-dollar',
  'sack-xmark',
  'safari',
  'sailboat',
  'salesforce',
  'sass',
  'satellite',
  'satellite-dish',
  'scale-balanced',
  'scale-unbalanced',
  'scale-unbalanced-flip',
  'schlix',
  'school',
  'school-circle-check',
  'school-circle-exclamation',
  'school-circle-xmark',
  'school-flag',
  'school-lock',
  'scissors',
  'screenpal',
  'screwdriver',
  'screwdriver-wrench',
  'scribd',
  'scroll',
  'scroll-torah',
  'sd-card',
  'searchengin',
  'section',
  'seedling',
  'sellcast',
  'sellsy',
  'server',
  'servicestack',
  'shapes',
  'share',
  'share-from-square',
  'share-nodes',
  'sheet-plastic',
  'shekel-sign',
  'shield',
  'shield-cat',
  'shield-dog',
  'shield-halved',
  'shield-heart',
  'shield-virus',
  'ship',
  'shirt',
  'shirtsinbulk',
  'shoe-prints',
  'shoelace',
  'shop',
  'shop-lock',
  'shop-slash',
  'shopify',
  'shopware',
  'shower',
  'shrimp',
  'shuffle',
  'shuttle-space',
  'sign-hanging',
  'signal',
  'signal-messenger',
  'signature',
  'signs-post',
  'sim-card',
  'simplybuilt',
  'sink',
  'sistrix',
  'sitemap',
  'sith',
  'sitrox',
  'sketch',
  'skull',
  'skull-crossbones',
  'skyatlas',
  'skype',
  'slack',
  'slash',
  'sleigh',
  'sliders',
  'slideshare',
  'smog',
  'smoking',
  'snapchat',
  'snowflake',
  'snowman',
  'snowplow',
  'soap',
  'socks',
  'solar-panel',
  'sort',
  'sort-down',
  'sort-up',
  'soundcloud',
  'sourcetree',
  'spa',
  'space-awesome',
  'spaghetti-monster-flying',
  'speakap',
  'speaker-deck',
  'spell-check',
  'spider',
  'spinner',
  'splotch',
  'spoon',
  'spotify',
  'spray-can',
  'spray-can-sparkles',
  'square',
  'square-arrow-up-right',
  'square-behance',
  'square-binary',
  'square-bluesky',
  'square-caret-down',
  'square-caret-left',
  'square-caret-right',
  'square-caret-up',
  'square-check',
  'square-dribbble',
  'square-envelope',
  'square-facebook',
  'square-font-awesome',
  'square-font-awesome-stroke',
  'square-full',
  'square-git',
  'square-github',
  'square-gitlab',
  'square-google-plus',
  'square-h',
  'square-hacker-news',
  'square-instagram',
  'square-js',
  'square-lastfm',
  'square-letterboxd',
  'square-minus',
  'square-nfi',
  'square-odnoklassniki',
  'square-parking',
  'square-pen',
  'square-person-confined',
  'square-phone',
  'square-phone-flip',
  'square-pied-piper',
  'square-pinterest',
  'square-plus',
  'square-poll-horizontal',
  'square-poll-vertical',
  'square-reddit',
  'square-root-variable',
  'square-rss',
  'square-share-nodes',
  'square-snapchat',
  'square-steam',
  'square-threads',
  'square-tumblr',
  'square-twitter',
  'square-up-right',
  'square-upwork',
  'square-viadeo',
  'square-vimeo',
  'square-virus',
  'square-web-awesome',
  'square-web-awesome-stroke',
  'square-whatsapp',
  'square-x-twitter',
  'square-xing',
  'square-xmark',
  'square-youtube',
  'squarespace',
  'stack-exchange',
  'stack-overflow',
  'stackpath',
  'staff-snake',
  'stairs',
  'stamp',
  'stapler',
  'star',
  'star-and-crescent',
  'star-half',
  'star-half-stroke',
  'star-of-david',
  'star-of-life',
  'staylinked',
  'steam',
  'steam-symbol',
  'sterling-sign',
  'stethoscope',
  'sticker-mule',
  'stop',
  'stopwatch',
  'stopwatch-20',
  'store',
  'store-slash',
  'strava',
  'street-view',
  'strikethrough',
  'stripe',
  'stripe-s',
  'stroopwafel',
  'stubber',
  'studiovinari',
  'stumbleupon',
  'stumbleupon-circle',
  'subscript',
  'suitcase',
  'suitcase-medical',
  'suitcase-rolling',
  'sun',
  'sun-plant-wilt',
  'superpowers',
  'superscript',
  'supple',
  'suse',
  'swatchbook',
  'swift',
  'symfony',
  'synagogue',
  'syringe',
  't',
  'table',
  'table-cells',
  'table-cells-column-lock',
  'table-cells-large',
  'table-cells-row-lock',
  'table-cells-row-unlock',
  'table-columns',
  'table-list',
  'table-tennis-paddle-ball',
  'tablet',
  'tablet-button',
  'tablet-screen-button',
  'tablets',
  'tachograph-digital',
  'tag',
  'tags',
  'tape',
  'tarp',
  'tarp-droplet',
  'taxi',
  'teamspeak',
  'teeth',
  'teeth-open',
  'telegram',
  'temperature-arrow-down',
  'temperature-arrow-up',
  'temperature-empty',
  'temperature-full',
  'temperature-half',
  'temperature-high',
  'temperature-low',
  'temperature-quarter',
  'temperature-three-quarters',
  'tencent-weibo',
  'tenge-sign',
  'tent',
  'tent-arrow-down-to-line',
  'tent-arrow-left-right',
  'tent-arrow-turn-left',
  'tent-arrows-down',
  'tents',
  'terminal',
  'text-height',
  'text-slash',
  'text-width',
  'the-red-yeti',
  'themeco',
  'themeisle',
  'thermometer',
  'think-peaks',
  'threads',
  'thumbs-down',
  'thumbs-up',
  'thumbtack',
  'thumbtack-slash',
  'ticket',
  'ticket-simple',
  'tiktok',
  'timeline',
  'toggle-off',
  'toggle-on',
  'toilet',
  'toilet-paper',
  'toilet-paper-slash',
  'toilet-portable',
  'toilets-portable',
  'toolbox',
  'tooth',
  'torii-gate',
  'tornado',
  'tower-broadcast',
  'tower-cell',
  'tower-observation',
  'tractor',
  'trade-federation',
  'trademark',
  'traffic-light',
  'trailer',
  'train',
  'train-subway',
  'train-tram',
  'transgender',
  'trash',
  'trash-arrow-up',
  'trash-can',
  'trash-can-arrow-up',
  'tree',
  'tree-city',
  'trello',
  'triangle-exclamation',
  'trophy',
  'trowel',
  'trowel-bricks',
  'truck',
  'truck-arrow-right',
  'truck-droplet',
  'truck-fast',
  'truck-field',
  'truck-field-un',
  'truck-front',
  'truck-medical',
  'truck-monster',
  'truck-moving',
  'truck-pickup',
  'truck-plane',
  'truck-ramp-box',
  'tty',
  'tumblr',
  'turkish-lira-sign',
  'turn-down',
  'turn-up',
  'tv',
  'twitch',
  'twitter',
  'typo3',
  'u',
  'uber',
  'ubuntu',
  'uikit',
  'umbraco',
  'umbrella',
  'umbrella-beach',
  'uncharted',
  'underline',
  'uniregistry',
  'unity',
  'universal-access',
  'unlock',
  'unlock-keyhole',
  'unsplash',
  'untappd',
  'up-down',
  'up-down-left-right',
  'up-long',
  'up-right-and-down-left-from-center',
  'up-right-from-square',
  'upload',
  'ups',
  'upwork',
  'usb',
  'user',
  'user-astronaut',
  'user-check',
  'user-clock',
  'user-doctor',
  'user-gear',
  'user-graduate',
  'user-group',
  'user-injured',
  'user-large',
  'user-large-slash',
  'user-lock',
  'user-minus',
  'user-ninja',
  'user-nurse',
  'user-pen',
  'user-plus',
  'user-secret',
  'user-shield',
  'user-slash',
  'user-tag',
  'user-tie',
  'user-xmark',
  'users',
  'users-between-lines',
  'users-gear',
  'users-line',
  'users-rays',
  'users-rectangle',
  'users-slash',
  'users-viewfinder',
  'usps',
  'ussunnah',
  'utensils',
  'v',
  'vaadin',
  'van-shuttle',
  'vault',
  'vector-square',
  'venus',
  'venus-double',
  'venus-mars',
  'vest',
  'vest-patches',
  'viacoin',
  'viadeo',
  'vial',
  'vial-circle-check',
  'vial-virus',
  'vials',
  'viber',
  'video',
  'video-slash',
  'vihara',
  'vimeo',
  'vimeo-v',
  'vine',
  'virus',
  'virus-covid',
  'virus-covid-slash',
  'virus-slash',
  'viruses',
  'vk',
  'vnv',
  'voicemail',
  'volcano',
  'volleyball',
  'volume-high',
  'volume-low',
  'volume-off',
  'volume-xmark',
  'vr-cardboard',
  'vuejs',
  'w',
  'walkie-talkie',
  'wallet',
  'wand-magic',
  'wand-magic-sparkles',
  'wand-sparkles',
  'warehouse',
  'watchman-monitoring',
  'water',
  'water-ladder',
  'wave-square',
  'waze',
  'web-awesome',
  'webflow',
  'weebly',
  'weibo',
  'weight-hanging',
  'weight-scale',
  'weixin',
  'whatsapp',
  'wheat-awn',
  'wheat-awn-circle-exclamation',
  'wheelchair',
  'wheelchair-move',
  'whiskey-glass',
  'whmcs',
  'wifi',
  'wikipedia-w',
  'wind',
  'window-maximize',
  'window-minimize',
  'window-restore',
  'windows',
  'wine-bottle',
  'wine-glass',
  'wine-glass-empty',
  'wirsindhandwerk',
  'wix',
  'wizards-of-the-coast',
  'wodu',
  'wolf-pack-battalion',
  'won-sign',
  'wordpress',
  'wordpress-simple',
  'worm',
  'wpbeginner',
  'wpexplorer',
  'wpforms',
  'wpressr',
  'wrench',
  'x',
  'x-ray',
  'x-twitter',
  'xbox',
  'xing',
  'xmark',
  'xmarks-lines',
  'y',
  'y-combinator',
  'yahoo',
  'yammer',
  'yandex',
  'yandex-international',
  'yarn',
  'yelp',
  'yen-sign',
  'yin-yang',
  'yoast',
  'youtube',
  'z',
  'zhihu',
]);
