context:
  development:
    organization: appsemble
    remote: http://localhost:9999
    visibility: public
    assets: true
    demoMode: true
  e2e:
    organization: appsemble
    visibility: public
    assets: true
    demoMode: true
  production:
    id: 1220
    organization: appsemble
    remote: https://appsemble.app
    visibility: public
    assets: true
    demoMode: true
    supportedLanguages: ['en', 'nl']
  review:
    organization: appsemble
    visibility: public
    assets: true
    demoMode: true
    supportedLanguages: ['en', 'nl']
  staging:
    id: 1220
    organization: appsemble
    remote: https://appsemble.eu
    visibility: public
    assets: true
    demoMode: true
    supportedLanguages: ['en', 'nl']
