context:
  development:
    organization: appsemble
    remote: http://localhost:9999
    template: true
    visibility: public
  production:
    id: 70
    organization: appsemble
    remote: https://appsemble.app
    template: true
    visibility: public
    supportedLanguages: ['en', 'nl']
  review:
    organization: appsemble
    template: true
    visibility: public
    supportedLanguages: ['en', 'nl']
  staging:
    id: 70
    organization: appsemble
    remote: https://appsemble.eu
    template: true
    visibility: public
    supportedLanguages: ['en', 'nl']
  e2e:
    organization: appsemble
    template: true
    visibility: public
