import { OpenAPIV3 } from 'openapi-types';

export const ActionDefinition: OpenAPIV3.NonArraySchemaObject = {
  oneOf: [
    { $ref: '#/components/schemas/DialogErrorActionDefinition' },
    { $ref: '#/components/schemas/DialogOkActionDefinition' },
    { $ref: '#/components/schemas/EmailActionDefinition' },
    { $ref: '#/components/schemas/FlowBackActionDefinition' },
    { $ref: '#/components/schemas/FlowFinishActionDefinition' },
    { $ref: '#/components/schemas/FlowNextActionDefinition' },
    { $ref: '#/components/schemas/LinkBackActionDefinition' },
    { $ref: '#/components/schemas/LinkNextActionDefinition' },
    { $ref: '#/components/schemas/NoopActionDefinition' },
    { $ref: '#/components/schemas/TeamJoinActionDefinition' },
    { $ref: '#/components/schemas/TeamListActionDefinition' },
    { $ref: '#/components/schemas/ThrowActionDefinition' },
    { $ref: '#/components/schemas/ConditionActionDefinition' },
    { $ref: '#/components/schemas/DialogActionDefinition' },
    { $ref: '#/components/schemas/EventActionDefinition' },
    { $ref: '#/components/schemas/FlowToActionDefinition' },
    { $ref: '#/components/schemas/LinkActionDefinition' },
    { $ref: '#/components/schemas/LogActionDefinition' },
    { $ref: '#/components/schemas/MessageActionDefinition' },
    { $ref: '#/components/schemas/RequestActionDefinition' },
    { $ref: '#/components/schemas/ResourceCountActionDefinition' },
    { $ref: '#/components/schemas/ResourceCreateActionDefinition' },
    { $ref: '#/components/schemas/ResourceDeleteActionDefinition' },
    { $ref: '#/components/schemas/ResourceGetActionDefinition' },
    { $ref: '#/components/schemas/ResourceQueryActionDefinition' },
    { $ref: '#/components/schemas/ResourceSubscriptionStatusActionDefinition' },
    { $ref: '#/components/schemas/ResourceSubscriptionSubscribeActionDefinition' },
    { $ref: '#/components/schemas/ResourceSubscriptionToggleActionDefinition' },
    { $ref: '#/components/schemas/ResourceSubscriptionUnsubscribeActionDefinition' },
    { $ref: '#/components/schemas/ResourceUpdateActionDefinition' },
    { $ref: '#/components/schemas/ShareActionDefinition' },
    { $ref: '#/components/schemas/StaticActionDefinition' },
  ],
};
