context:
  development:
    organization: appsemble
    remote: http://localhost:9999
    visibility: public
    resources: true
  e2e:
    organization: appsemble
    remote: http://appsemble:9999
    template: true
    visibility: public
    resources: true
  production:
    id: 1129
    organization: appsemble
    remote: https://appsemble.app
    visibility: public
    resources: true
  review:
    organization: appsemble
    visibility: public
    resources: true
  staging:
    organization: appsemble
    remote: https://staging.appsemble.review
    visibility: public
    resources: true
