context:
  development:
    organization: appsemble
    remote: http://localhost:9999
    visibility: public
    resources: true
  e2e:
    organization: appsemble
    visibility: public
    resources: true
  production:
    id: 1129
    organization: appsemble
    remote: https://appsemble.app
    visibility: public
    resources: true
    supportedLanguages: ['en', 'nl']
  review:
    organization: appsemble
    visibility: public
    resources: true
    supportedLanguages: ['en', 'nl']
  staging:
    id: 1129
    organization: appsemble
    remote: https://appsemble.eu
    visibility: public
    resources: true
    supportedLanguages: ['en', 'nl']
