context:
  development:
    organization: appsemble
    remote: http://localhost:9999
    template: true
    visibility: public
  production:
    id: 1194
    organization: appsemble
    remote: https://appsemble.app
    template: true
    visibility: public
  review:
    organization: appsemble
    template: true
    visibility: public
  staging:
    id: 1194
    organization: appsemble
    remote: https://staging.appsemble.eu
    template: true
    visibility: public
  e2e:
    organization: appsemble
    template: true
    visibility: public
