context:
  development:
    organization: appsemble
    remote: http://localhost:9999
    visibility: public
  production:
    organization: appsemble
    remote: https://appsemble.app
    visibility: public
    id: 1299
  review:
    organization: appsemble
    visibility: public
  staging:
    organization: appsemble
    remote: https://appsemble.eu
    visibility: public
    id: 1299
  e2e:
    organization: appsemble
    visibility: public
