graph BT
  subgraph Docker Container
    A(Database) --> B
    B("Server (API)") --> A
    C(App) --> B
    B --> C
    D(Editor) --> B
    B --> D
  end
  E(CLI) --> B
  F(SDK) --> E
  G(Block) --> F
