graph TD
    A(App Block) --> B(App Core)
    B --> C(App Shared)
    C --> D(Organization Block)
    D --> E(Organization Core)
    E --> F(Organization Shared)
    F --> G(Server Block)
    G --> H(Server Core)
    H --> I(Server Shared)
    I --> J["Default Style (Bulma CSS)"]
