context:
  development:
    organization: appsemble
    remote: http://localhost:9999
    template: true
    visibility: public
    resources: true
    assets: true
    assetsClonable: true
  production:
    id: 369
    organization: appsemble
    remote: https://appsemble.app
    template: true
    visibility: public
    resources: true
    assets: true
    assetsClonable: true
  review:
    organization: appsemble
    template: true
    visibility: public
    resources: true
    assets: true
    assetsClonable: true
  staging:
    id: 369
    organization: appsemble
    remote: https://staging.appsemble.review
    template: true
    visibility: public
    resources: true
    assets: true
    assetsClonable: true
  e2e:
    organization: appsemble
    remote: http://appsemble:9999
    template: true
    visibility: public
    resources: true
    assets: true
    assetsClonable: true
