context:
  development:
    organization: appsemble
    remote: http://localhost:9999
    visibility: public
    resources: true
    assets: true
    assetsClonable: true
  production:
    id: 369
    organization: appsemble
    remote: https://appsemble.app
    visibility: public
    resources: true
    assets: true
    assetsClonable: true
  review:
    organization: appsemble
    visibility: public
    resources: true
    assets: true
    assetsClonable: true
  staging:
    id: 369
    organization: appsemble
    remote: https://appsemble.eu
    visibility: public
    resources: true
    assets: true
    assetsClonable: true
  e2e:
    organization: appsemble
    visibility: public
    resources: true
    assets: true
    assetsClonable: true
