export const serverActions = new Set([
  'noop',
  'throw',
  'condition',
  'each',
  'email',
  'log',
  'notify',
  'request',
  'resource.get',
  'resource.query',
  'resource.create',
  'resource.patch',
  'resource.update',
  'resource.delete',
  'static',
]);
