export const {
  apiUrl,
  appControllerCode,
  appControllerImplementations,
  appUpdated,
  blockManifests,
  definition,
  demoMode,
  development,
  enableSelfRegistration,
  id: appId,
  languages,
  logins,
  sentryDsn,
  sentryEnvironment,
  showAppsembleLogin,
  showAppsembleOAuth2Login,
  showDemoLogin,
  vapidPublicKey,
} = window.settings;
delete window.settings;
