context:
  development:
    organization: appsemble
    remote: http://localhost:9999
    template: true
    visibility: public
  production:
    id: 9
    remote: https://appsemble.app
    template: true
    visibility: public
  review:
    organization: appsemble
    template: true
    visibility: public
  staging:
    visibility: public
    remote: https://staging.appsemble.review
    template: true
    organization: appsemble
  e2e:
    organization: appsemble
    remote: http://appsemble:9999
    template: true
    visibility: public
