import { Options } from '@appsemble/node-utils/server/types';

import {
  checkRole,
  createResourcesWithAssets,
  createSettings,
  createTheme,
  deleteAppResource,
  getApp,
  getAppAssets,
  getAppBlockStyles,
  getAppDetails,
  getAppIcon,
  getAppMessages,
  getAppResource,
  getAppResources,
  getAppScreenshots,
  getAppStyles,
  getAppUrl,
  getBlockAsset,
  getBlocksAssetsPaths,
  getCsp,
  getDbUpdated,
  getHost,
  getTheme,
  parseQuery,
  updateAppResource,
  verifyPermission,
} from './index.js';

export const options: Options = {
  checkRole,
  createResourcesWithAssets,
  createSettings,
  createTheme,
  deleteAppResource,
  getApp,
  getAppAssets,
  getAppBlockStyles,
  getAppDetails,
  getAppIcon,
  getAppMessages,
  getAppResource,
  getAppResources,
  getAppScreenshots,
  getAppStyles,
  getAppUrl,
  getBlockAsset,
  getBlocksAssetsPaths,
  getCsp,
  getDbUpdated,
  getHost,
  getTheme,
  parseQuery,
  updateAppResource,
  verifyPermission,
};
